lib/fragment.js, lib/request-handler.js
I did a small refactor of the fragment's code, removed two streams, and made request of the async stream immediately return placeholder div.
=> Small refactor of the fragment

lib/fragment.js, lib/request-handler.js
=> Improve primary handle

lib/serializer.js, tests/handle-tag.js, tests/serializer.js, tests/tailor.js
This PR addresses two things. 
+ fixes the issue with handle tags #48 
+ Add support for the nested fragments
=> add support for flattening nested fragments

src/pipe.js
- This fixes the regression issue on FF 
- Issue here - https://bugzilla.mozilla.org/show_bug.cgi?id=1203973
=> update loadCss to fix firefox crash issue on 38

lib/fragment.js, src/pipe.js, tests/tailor.js
+ Will allow us to capture the initialisation cost for each fragments on the page.
=> capture metrics for fragment initialization

example/tailor.js, lib/fetch-template.js, lib/request-handler.js
=> Builtin fetch template: async and handle not found

example/tailor.js, index.js, package.json
+ inlining small AMD loader would improve our first paint time. 
+ backwards compatible with specifying AMD loader url.
=> allow AMD loader to be inlined (closes #73)

.gitignore, lib/fragment.js, lib/request-fragment.js, package.json, tests/request-fragment.js, tests/tailor.js
+ picking @ytanruengsri commits  from #76 and did some modifications
=> Support fragment level compression  

.eslintignore, lib/fetch-template.js, lib/filter-headers.js, lib/parse-template.js, lib/request-fragment.js, lib/request-handler.js, lib/serializer.js, lib/transform.js
Adding JSDoc style documentation to the code.
=> Documentation

.travis.yml, package.json
- The badge redirect URLs are incorrect. Updated with correct URLs
=> Fix the badge redirect URLs in README

.eslintignore, lib/parse-template.js, lib/serializer.js, tests/serializer.js
=> html compatible for script tags

lib/fragment.js, tests/streams/async-stream.js
=> test for async stream error handling

docs/Performance.md
Generated using http://doctoc.herokuapp.com/
=> Added toc to perfomance doc page in order to make it more convinient to navigate

.travis.yml, lib/request-handler.js, tests/tailor.js
=> [Perf] Preload primary fragment's assets [fixes #127]

examples/multiple-fragments-with-custom-amd/fragment.js, examples/multiple-fragments-with-custom-amd/templates/base-template.html, lib/request-handler.js, tests/tailor.js
+ To fix the double requests when things are changed dynamically though requirejs hooks
=> fix the preload headers for crossorigin requests

examples/multiple-fragments-with-custom-amd/test.js
Testing async rendering and slots merging to base templates.
=> fix integration test and bump IE version 10

.travis.yml
This PR includes:
* 💅 
* Add Yarn cache, see https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
=> Add Yarn cache (Travis CI)

README.md, examples/multiple-fragments-with-custom-amd/fragment.js, examples/multiple-fragments-with-custom-amd/index.js, examples/multiple-fragments-with-custom-amd/templates/base-template.html, examples/multiple-fragments-with-custom-amd/test.js, index.js, lib/fragment.js, lib/request-handler.js, package.json, tests/tailor.js, yarn.lock
As suggested in #136 - adding an option to allow more than a single Header-Link for css and javascript.
=> Multiple link rel headers

CONTRIBUTING.md
Just edited file to fix markup formatting issues.
=> Fixing markup formatting issues.

src/pipe.js
+ This allows hooks to be called for fragments that does not have a default init function exposed. 
+ Also hoisted the fn creation
=> custom hooks should be called for all fragments

CHANGELOG.md, package.json
+ Custom hooks fix for fragments without default init function
=> release new version 3.0.1

lib/fetch-template.js, tests/fetch-template.js
+ tests when templatesPath is specified as file instead of dir
=> add tests - file in templatesPath

CHANGELOG.md, package.json
+ new minor version bump with few changes #172 #174 #175
=> Publish new version 3.1.1

package.json, tests/serializer.js, tests/tailor.js
+ small changes before we release a new version.
=> Improve code coverage for requestHandler & serializer

CHANGELOG.md, package.json
=> release 3.2.1

CHANGELOG.md, package.json
+ minor release with the new feature to add support for custom performance entry #187
=> release version 3.3.0

CHANGELOG.md
Forgot to add that we also had one more fix from @ruiaraujo
=> Add missing changelog record

docs/Performance.md
=> copied expnations from PR #187 to doc

CHANGELOG.md, package.json
=> release version 3.5.0

index.js, tests/tailor.js
+ Missed to while doing preloading feature, was missed easily because of no tests. The preloaded script url was different from piped script url
+ Added the tests for piping.
=> (fix) Pipe the loader(AMD) script url from extended options

CHANGELOG.md, package.json
=> release version 3.5.1

README.md, lib/fragment.js, tests/fragment.js
=> 207 custom attributes

CHANGELOG.md, package.json
+ Update package.json and changelog.md
=> tailor release - v3.6.0

CHANGELOG.md, package.json
=> release version 3.7.0[skip ci]

CHANGELOG.md, package.json
+ release 3.8.0 - [changelog](https://github.com/zalando/tailor/blob/7dd3513e837aa39f51befe68e3a4878fb7e35e32/CHANGELOG.md#380)
=> release version 3.8.0[skip ci]

CHANGELOG.md, package.json
+ changelog https://github.com/zalando/tailor/blob/1a3abd7de51043c409051d35601ab153eb15bcb7/CHANGELOG.md#392
=> release version 3.9.2

.eslintignore, .travis.yml, examples/fragment-performance/hooks.js, examples/fragment-performance/test.js, package.json
Close #300 
- Run puppeteer test for PR and let the selenium fail for PR 
- Change Travis matrix to jobs
=> feat: Run puppeteer test for PR and let the selenium fail for PR

.zappr.yaml
+ Accept approvals from zalando org and collaborators.
=> chore: accept approval from collaborators

lib/serializer.js, tests/tailor.js
a slot named default will duplicate the content, the PR fix it #295
=> fix: allow slot named default

lib/fragment.js, tests/fragment.js, tests/tailor.js
=> (new): introducing custom attributes (fixes #287)
