lib/fragment.js
lib/request-handler.js
lib/streams/async-stream.js
lib/streams/buffer-concat-stream.js
lib/streams/content-length-stream.js
package.json
tests/streams/async-stream.js
tests/streams/buffer-concat-stream.js
tests/streams/content-length-stream.js
tests/streams/layout-streams.js

I got rid of manually handling `.on('data'..` events where possible by introducing `ContentLengthStream` and `BufferConcatStream`. I also got rid of additional `PassThrough` for the stringifier output.

Added buffer-concat and content-length streams

---

index.js
lib/streams/parser-stream.js
tests/streams/layout-streams.js

We should insert pipe definition before the fist fragment or the first script tag.

Set tags before which the pipe should be inserted

---

example/templates/index.html
lib/fragment.js
src/pipe.js
tests/tailor.js

Sometimes tracking scripts will append some scripts to the DOM, so we need to distinguish between their scripts and ours.

Fixed detection of the current script

---

lib/streams/stringifier-stream.js

`Warning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit`.
Addresses this error, by keeping the listeners in control. This will make sure we get error message if an actual leak occurred.

Increase listeners for concurrent handlers on stream

---

example/fragment.js

Small change but when break is missing causes issues when trying to convert example to pull css from files.

add missing break in example

---

lib/serializer.js
tests/tailor.js

This will allow us to insert contents anywhere in the parent template without ugly slot name magic in the child templates.

introduce unnamed slot behaviour

---

src/pipe.js

+ This is a backward compatible change
fixes #92

Allow lazy fragment initializaiton through promise

---

README.md

I noticed when searching through the code and a co-worker informing me that Tailor has support for AWS' special header format but it wasn't documented anywhere, this commit adds a note to the Readme to highlight this support.

Add Link alias note

---

README.md
index.js
lib/filter-headers.js
lib/fragment.js
lib/request-fragment.js
lib/request-handler.js
tests/filter-headers.js
tests/fragment.events.js
tests/request-fragment.js
tests/tailor.js

+ Document new options
+ Allow headers to be configurable before forwarding to fragments
+ refactor fragment options. 
fix #97 #104

configurable options for headers & refactoring [fixes #91, 104]

---

tests/request-fragment.js
tests/tailor.js

Previously, assertion failures would not have been displayed correctly in the test output.

Handle assertion failures in promises better

---

package.json

+ fixes #131 
This breaks our `pipe.min.js` and converts the return statement inside IIFE to a block statement. 
Introduced as part of - https://github.com/mishoo/UglifyJS2/pull/1522
Reminds me that we should use `yarn.lock/shrinkwrap.json` to lock down the versioning of deps.

fix uglify options to preserve implicit return

---

lib/request-handler.js
tests/tailor.js

Disabling the HTTP/2 server push until the day when cache-digests are supported in browsers and all HTTP/2 pushed resources are HTTP cache aware. 
This will also help avoid undesired server behaviour for preloaded resources via `Link` Headers
More details in the SPEC https://w3c.github.io/preload/#server-push-http-2

opt out of server push for preloaded resources

---

lib/request-handler.js
tests/tailor.js

+ The old way of preloading logic is buggy and creates sync issues because it was based on events. 
This is cleaner approach and fixes the issue with preloading wrong assets for previously rendered page. This scenario is hard to test because of the way events work and you would need to loadtest the system to really create this scenario.

fix issue with preloading wrong assets on pages

---

lib/request-handler.js

+  write the response headers only one
+ Fire the response event only after extracting the preload headers.

Write response headers only once

---

.travis.yml
index.js
lib/fragment.js
lib/serializer.js
perf/fragment-server.js
tests/handle-tag.js
tests/streams/buffer-concat-stream.js
tests/streams/content-length-stream.js
tests/tailor.events.js
tests/tailor.js

- closes #149 
- Update Buffer to use Node v8 syntax

Update Buffer to use Node v8 syntax

---

lib/fetch-template.js
tests/fetch-template.js

+ Error was not rethrown before back to the fetchTemplate function
+ Added a test case for the missing case.

propagate the error properly to tailor errors [fixes #178]

---

lib/process-template.js
lib/request-handler.js
tests/process-template.js

+ uses the existing fragment event for primary
+ added jsdoc

remove special event for handling primary

---

lib/request-handler.js

+ the serialised parsed template is always an array.

remove uncessary check for parse result

---

lib/request-handler.js
lib/streams/stringifier-stream.js
tests/tailor.js

Right now asyncStream ends as soon as we stop pushing things to the stringifier stream, which means we can't push things to asyncStream from our customer tags in handleTag.
To support async fragments there we need to end asyncStream later. It seem like proper place would be to end it right before piping it into the resulting stream. I could either do it in the stringifier stream, but though that it'd be better to do via events (`plugged` event).

End asyncStream later in the process (before piping)

---

src/pipe.js

This PR adds the support for fragment teams to add custom metrics that looks similar to [PerformanceEntry](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceEntry) that can be retrieved via tailor in addition to the [hooks](https://github.com/zalando/tailor/blob/master/docs/hooks.md#front-end-hooks) it supports. 
```js
Pipe.addPerfEntry("time-to-meaningful-paint", 2000.00) // done from some fragment on some page
Pipe.getEntries()
// [{
name: "time-to-meaningful-paint",
duration: 2000.00,
entryType: "tailor",
startTime: // start time relative to navigation start
}]
```
Browsers right now does not expose an API for creating custom PerformanceEntry and make them available on PerformanceTimeline.
+ User Timing - `mark` and `measure` does not allow a way for pushing custom timing …

add support for custom performance entries

---

lib/transform.js
tests/parse-template.js

For some reason tailor fails to parse templates with HTML comments inside.
Judging by the error message and some snippets in the code, it seem like handling of comments is different from how other tags are processed.
```
TypeError: Cannot destructure property `slot` of 'undefined' or 'null'.
at nodes.forEach.node (lib/transform.js:56:51)
at Array.forEach (<anonymous>)
at Transform._groupSlots (lib/transform.js:54:15)
at Transform.applyTransforms (lib/transform.js:32:24)
at Promise.resolve.then.transform (lib/parse-template.js:19:19)
at <anonymous>
```

Tailor fails to parse template with comments inside

---

README.md
lib/filter-headers.js
tests/filter-headers.js

Add x-request-host and x-request-uri headers to allow passing down information to fragments that will not be filtered out by default.
Based on discussion in https://github.com/zalando/tailor/issues/189

Add x-request-host and x-request-uri headers

---

CHANGELOG.md
package.json

* Two headers (`x-request-uri` & `x-request-host`) are added to the whitelist along with documentation on how to use them ([#192](https://github.com/zalando/tailor/pull/192))

Release version 3.4.0

---

README.md

The examples provided by default through Tailor are great to get started, but I think linking directly to the SPA examples in the README would be helpful to those looking to dive a bit deeper into more complex and practical usage of Tailor (similar to the techniques used by Zalando in production).
The second of the two example SPAs was built in response to a dependency handling issue (#196)

Include demo SPA repos in README

---

lib/transform.js
tests/parse-template.js
tests/transform.js

+ Parse comments in child templates without error. 
+ Successor #191

parse comment tags without error in child templates

---

index.js
lib/process-template.js
lib/request-handler.js
lib/utils.js
tests/tailor.js

+ Fixes #202 
+ While working on this feature, figured out a Chrome bug which causes the module loader script in preload cache to be ignored. 
Link to the bug - bugs.chromium.org/p/chromium/issues/detail?id=794958
+ With this fix, loader script should be the first to be requested, Check before and after
**Before**
**After**
Works only in prime cache because of the chrome bug.

Prioritize the module loader script with link headers

---

src/pipe.js

+ The previous API for adding performance entries to the page is pretty neat and already helps fragments to add custom timing information at every point of the render phase. But it lacks the uniformity and it will be pretty hard to use it for monitoring or any other purpose since the naming is quite different on every page. 
+ Meaningful paint is different for each page and its hard to measure from tailor since tailor has no context of elements being rendered from fragments. Its best to keep the logic in fragments. 
The current API is just a proxy to the old `Pipe.addPerfEntry` 
```js
Pipe.addTTFMPEntry(2000);
Pipe.getEntries()
// [{
duration: 2000
​​entryType: "tailor"
name: "ttfmp"
startTime: 67.58
}]
```
+ This API will be used only when primary fragments decide that the page is …

add custom api for adding ttfmp from fragments

---

examples/fragment-performance/hooks.js
examples/fragment-performance/index.js
examples/fragment-performance/templates/index.html

While measuring timing groups, we forgot to account for fragments that might be streamed asynchronously or streamed lazily on the page. When this happens, the Pipe start would fire a lot late and script execution would not even fire which results in wrong metrics being captured
I have changed the logic to keep adding timing information to the same group name whenever we find fragments of same timing group. This would ensure that even if have fragments that are streamed later, we get the correct value. 
We can use Tailor custom performance API, `addPerfEntry` to add all the timings that we have captured.
** Downside of the approach is that we wont see the timing groups information in Chrome's User timing view **

account for lazy streamed fragment scripts

---

src/pipe.js

+ if fragment init code returns null, pipe would explode and throw runtime error
+ Thanks to Ingvar Stepanyan - https://twitter.com/RReverser/status/986687943602352128

fix: add null check while lazy rendering

---

lib/utils.js
tests/tailor.js

Adding support to aws custom headers when preloading assets.

fix assets preload for primary fragments on aws s3 (#228)

---

README.md
examples/basic/index.js
examples/basic/templates/index.html
index.d.ts
index.js
lib/fragment.js
lib/parse-template.js
lib/process-template.js
lib/request-fragment.js
lib/request-handler.js
lib/tracing.js
package.json
yarn.lock

This addresses #231 
The server request handling and fetching of fragments are instrumented. There are some caveats with the instrumentations of Fragment.fetch():
- A new optional argument is passed to the nested functions so that it's possible to reference the parent Span
- It's possible to pass a custom fetchFragment function which doesn't handle the new parentSpan parameter. To guarantee span context propagation, those custom functions should handle the new parameter and propagate it using the appropriate carrier. For HTTP the default implementation can be used as a reference
Tailor will use, by default the "NoOpTracer" which is part of the standard OpenTracing libraries. This tracer implementation discards all the spans collected.
To use a Tracer from other vendors (Jaeger, Lighstep, …

added opentracing instrumentation

---

examples/basic/index.js

remove misplaced semicolon from documentation example

docfix: remove semicolon from object literal

---

lib/request-handler.js

+ If we respond with a empty message with Content-Type: 'text/html', the browser will throw error stating as **This page isn’t working** losing the original error page. 
+ Now we respond with 500 status code and Internal Server Error as the response when there is a parse error or when there is no fallback provided for primary fragment. 
This is a very old bug and it was introduced when we started supporting fallbacks and I noticed after we started the Opentracing instrumentation, so Thanks to @lmineiro  😄

fix: handle parsing & primary error properly

---

lib/fragment.js
lib/request-handler.js
tests/fragment.events.js
tests/tailor.js

+ Fix the issue when the parent span(handle-request) was getting finished before the child span(fetch-fragment) is finished. 
+ Add tests for the opentracing instrumentation using [MockTracer](https://opentracing-javascript.surge.sh/classes/mocktracer.html)

refactor(opentracing): add tests and pass correct span contexts

---

lib/request-handler.js

After giving it some more thought, I believe the most appropriate name for the edge request in Tailor should be `compose-page`.
It follows the rationale that Tailor is a **Composition Service** and the requests it receives are requests aimed at **composing a page**. `compose-page` follows [the conventions](https://github.com/opentracing/specification/blob/master/specification.md#start-a-new-span) that we also have adopted so far - a verb and the object related to such verb.

renamed operation name

---

lib/fragment.js
tests/tailor.js

Renamed the `url` tag to `http.url`, according to [OpenTracing's semantic conventions](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table)

applied opentracing semantic conventions

---

docs/hooks.md
examples/fragment-performance/hooks.js
examples/fragment-performance/templates/index.html
src/pipe.js
tests/streams/stringifier-stream.js

+ Having multiple subscribers in onDone performance hook will enable us do post processing of all the metrics and also do reporting in different parts of the application.
+ We do not need multiple subscribers in other hooks since it will make it hard to measure the fragment script exec times. 
+ We are not using pub,sub pattern where we would normally push in to array and call the subscribers, Instead we are chaining the callbacks to make the code simpler and also backwards compatible.

introduce multiple subscribers for on done hook

---

lib/filter-headers.js
lib/fragment.js
lib/request-handler.js
tests/fragment.js
tests/tailor.js

small optimisation on fragment attributes computation
+ attributes object shape is fixed to minimal set of keys
+ pipe attributes computation is done once instead of multiple times. 
```
Stat         Avg     Stdev  Max
Latency (ms) 435.94  107.18 984.88
Req/Sec      224.9   47.2   278
Bytes/Sec    2.93 MB 621 kB 3.64 MB
```
```
Stat         Avg     Stdev  Max
Latency (ms) 382.2   93.89  994.23
Req/Sec      257     57.96  315
Bytes/Sec    3.36 MB 768 kB 4.13 MB
```

(perf): minor optimization on attributes extraction

---

lib/fragment.js
lib/parse-link-header.js
lib/request-handler.js
lib/utils.js
package.json
tests/parse-link-header.js
tests/tailor.js
yarn.lock

+ Roll our own fine tuned parse link header implementation based on https://github.com/thlorenz/parse-link-header
+ Avoid double parsing of link headers on fragment response and while preloading
+ Keep fragment object shape static

(perf): improve parsing of link header from fragments

---

lib/fragment.js
lib/request-handler.js

Updated span name to follow the conventions:
https://github.bus.zalan.do/SRE/opentracing/blob/master/wg-semantic-conventions/best-practices.md

Update span names to follow Opentracing conventions

---

lib/streams/stringifier-stream.js
tests/streams/stringifier-stream.js

Previously we were consuming and processing the fragment streams in order they were declared in the template. This PR does the following things
+ Consume the fragment streams on fragment buffer in parallel and process them in series while flushing them in to the client to guarantee the order in which fragments are declared on the page. 
+ This would ideally improve the time to last byte and latency. Check benchmarks below. 
**Note**: One caveat  might be increase in the memory usage of the application since we are buffering the response. We are clearing the buffer once the stream is written to the output stream, But it might be a issue if fragments are sending huge data. We can figure this out and warn by listening on `fragment:response` event which has the size of response
In order to …

(perf) consume streams in parallel and flush them in series

---

lib/streams/stringifier-stream.js
tests/streams/stringifier-stream.js

This is a edge case because stringifier deals only with fragment streams which are not supposed to be in object mode, But using handleTags, we can parse arbitrary tags and send streams in objectMode to the response stream. 
Since [`decodeStrings`](https://nodejs.org/api/stream.html#stream_constructor_new_stream_writable_options) is set to true for fragment streams, all data will be passed as buffers and Buffer.concat would work well. But on objectMode streams, this will not happen and chunks are not decoded as buffers instead left as [arbitrary data chunks](https://github.com/nodejs/node/blob/master/lib/_stream_writable.js#L338)
This PR handles this case when chunks are not buffers. 
Without this fix, we will see an issue like this, 
```js
Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The …
```

(fix): handle streams in object mode while buffering

---

lib/fragment.js

+ when error happens during unzipping, its a broken response and it should be marked as error.

mark span as error on unzip failure

---

lib/fragment.js
tests/tailor.js

+ Helps in tracing when there are timeout issues with the remote fragment endpoint.

opentracing: add timeout tag to fragment spans

---

README.md

The existing `example/fragment.js` doesn’t exist; I’m guessing this is the correct example to link to if showing off how to use the `Link` header is important here

Fix README link to basic example with CSS+JS Link headers

---

index.d.ts

Currently, trying to implement  your own fetchTemplate in typescript respecting the implementation will throw this type error:
```
Type '(request: IncomingMessage, parseTemplate: any) => any' is not assignable to type '(templatesPath: string, baseTemplateFn: (path: string) => string) => Promise<any>'.
```
This pull request fixes the types according to the current implementation, also adding a `ParseTemplateFunction` type

fix: fetchTemplate option type
